spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # hibernate 초기화 이후 schema.sql 실행
  profiles:
    include: secret

  sql:
    init:
      mode: always  # 모든 데이터베이스로 초기화 대상 변경

  data:
    web:
      pageable:
        one-indexed-parameters: true  # 페이징 0부터가 아닌 1부터

logging.level:
  org.hibernate.SQL: debug