spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false # hibernate 초기화 이후 schema.sql 실행
  datasource:
    hikari:
      max-lifetime: 177000
  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: never  # 모든 데이터베이스로 초기화 대상 변경

logging.level:
  org.hibernate.SQL: info

oauth:
  kakao:
    redirect-uri: https://www.gomin.my/oauth/kakao/callback  # 운영 도메인으로 변경
  google:
    redirect-uri: https://www.gomin.my/oauth/google/callback  # 운영 도메인으로 변경