spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost # 권장 x ip 주소로...

  sql:
    init:
      mode: always

logging.level:
  org.hibernate.SQL: info

logging:
    level:
      com.zaxxer.hikari.HikariConfig: DEBUG
      com.zaxxer.hikari: TRACE

oauth:
  kakao:
    redirect-uri: http://localhost:5173/oauth/kakao/callback  # 운영 도메인으로 변경
  google:
    redirect-uri: http://localhost:5173/oauth/google/callback  # 운영 도메인으로 변경