export const modalStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "55vh",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  postOuterBox: {
    position: "relative",
    width: "55vh",
    height: "55vh",
    maxWidth: "500px",
    maxHeight: "500px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  postIt: {
    position: "relative",
    width: "55vh",
    height: "55vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  postItImage: {
    position: "absolute",
    top: "0",
    right: "0%",
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  closeButton: {
    position: "absolute",
    top: "17%",
    right: "22%",
    cursor: "pointer",
    fontSize: "2.3vh",
    zIndex: 3,
    color: "#000000",
  },
  content: {
    position: "relative",
    margin: "10px 0",
    zIndex: 2,
    width: "28vh",
    height: "auto",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "2vh",
    bottom: "5%",
  },
  heart: {
    position: "absolute",
    bottom: "25%",
    right: "20%",
    fontSize: "28px",
    zIndex: 3,
    cursor: "pointer",
  },
  pawPrint: {
    position: "absolute",
    bottom: "25%",
    right: "20%",
    fontSize: "28px",
    zIndex: 3,
    color: "#4a4a4a",
  },
  gptDisclaimer: {
    position: "absolute",
    bottom: "25%",
    left: "20%",
    fontSize: "1.4vh",
    color: "#666666",
    zIndex: 3,
  },
};
